name: Site build CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - run: git config --global user.email "git.page.story@gmail.com"
    - run: git config --global user.name  "git-story-bot"

    - name: Add product remote
      env:
        BOT_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: git clone https://git-story:${BOT_TOKEN}@github.com/git-story/git-story.github.io.git product

    - name: Add preivew remote
      env:
        BOT_TOKEN: ${{ secrets.BOT_GITHUB_TOKEN }}
      run: git clone https://git-story:${BOT_TOKEN}@github.com/git-story/preview.git preview

    - run: npm ci
    - run: npm run build
    - run: rm -rf node_modules package-lock.json
