name: build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build
    - name: product push
      uses: git-story/git-story.github.io@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'product site build'
        force-add: 'true'
        name: 'Github Actions'
        email: 'git.page-story@gmail.com'
        file-path: |
          product/**
    - name: preview push
      uses: git-story/preview@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'preview site build'
        force-add: 'true'
        name: 'Github Actions'
        email: 'git.page-story@gmail.com'
        file-path: |
          preview/**
